import { Container, interfaces } from 'inversify';
import { TYPES } from './types';
import { EventSender } from '../client/eventSender';
import { CDTPBreakpointFeaturesSupport } from '../cdtpDebuggee/features/cdtpBreakpointFeaturesSupport';
import { IStackTracePresentationLogicProvider, StackTracesLogic } from '../internal/stackTraces/stackTracesLogic';
import { SourcesLogic } from '../internal/sources/sourcesLogic';
import { CDTPScriptsRegistry } from '../cdtpDebuggee/registries/cdtpScriptsRegistry';
import { ClientToInternal } from '../client/clientToInternal';
import { InternalToClient } from '../client/internalToClient';
import { BreakpointsLogic } from '../internal/breakpoints/breakpointsLogic';
import { PauseOnExceptionOrRejection } from '../internal/exceptions/pauseOnException';
import { Stepping } from '../internal/stepping/stepping';
import { DotScriptCommand } from '../internal/sources/features/dotScriptsCommand';
import { BreakpointsRegistry } from '../internal/breakpoints/breakpointsRegistry';
import { ReAddBPsWhenSourceIsLoaded } from '../internal/breakpoints/features/reAddBPsWhenSourceIsLoaded';
import { PauseScriptLoadsToSetBPs } from '../internal/breakpoints/features/pauseScriptLoadsToSetBPs';
import { BPRecipieAtLoadedSourceLogic } from '../internal/breakpoints/bpRecipieAtLoadedSourceLogic';
import { DeleteMeScriptsRegistry } from '../internal/scripts/scriptsRegistry';
import { SyncStepping } from '../internal/stepping/features/syncStepping';
import { AsyncStepping } from '../internal/stepping/features/asyncStepping';
import { CDTPExceptionThrownEventsProvider } from '../cdtpDebuggee/eventsProviders/cdtpExceptionThrownEventsProvider';
import { CDTPExecutionContextEventsProvider } from '../cdtpDebuggee/eventsProviders/cdtpExecutionContextEventsProvider';
import { CDTPInspectDebugeeState } from '../cdtpDebuggee/features/cdtpInspectDebugeeState';
import { CDTPUpdateDebugeeState } from '../cdtpDebuggee/features/cdtpUpdateDebugeeState';
import { SmartStepLogic } from '../internal/features/smartStep';
import { LineColTransformer } from '../../transformers/lineNumberTransformer';
import { ChromeDebugLogic } from '../chromeDebugAdapter';
import { CDTPOnScriptParsedEventProvider } from '../cdtpDebuggee/eventsProviders/cdtpOnScriptParsedEventProvider';
import { CDTDebuggeeExecutionEventsProvider } from '../cdtpDebuggee/eventsProviders/cdtpDebuggeeExecutionEventsProvider';
import { CDTPDebuggeeBreakpoints } from '../cdtpDebuggee/features/cdtpDebuggeeBreakpoints';
import { IDOMInstrumentationBreakpoints, CDTPDOMDebugger } from '../cdtpDebuggee/features/cdtpDOMInstrumentationBreakpoints';
import { CDTPBrowserNavigator } from '../cdtpDebuggee/features/cdtpBrowserNavigator';
import { CDTPLogEventsProvider } from '../cdtpDebuggee/eventsProviders/cdtpLogEventsProvider';
import { CDTPConsoleEventsProvider } from '../cdtpDebuggee/eventsProviders/cdtpConsoleEventsProvider';
import { IAsyncDebuggingConfigurer, CDTPAsyncDebuggingConfigurer } from '../cdtpDebuggee/features/CDTPAsyncDebuggingConfigurer';
import { IScriptSourcesRetriever, CDTPScriptSourcesRetriever } from '../cdtpDebuggee/features/CDTPScriptSourcesRetriever';
import { CDTPDebugeeExecutionController } from '../cdtpDebuggee/features/cdtpDebugeeExecutionController';
import { CDTPPauseOnExceptionsConfigurer } from '../cdtpDebuggee/features/CDTPPauseOnExceptionsConfigurer';
import { CDTPDebugeeSteppingController } from '../cdtpDebuggee/features/CDTPDebugeeSteppingController';
import { CDTPDebugeeRuntimeVersionProvider } from '../cdtpDebuggee/features/cdtpDebugeeRuntimeVersionProvider';
import { CDTPBlackboxPatternsConfigurer } from '../cdtpDebuggee/features/cdtpBlackboxPatternsConfigurer';
import { CDTPDomainsEnabler } from '../cdtpDebuggee/infrastructure/cdtpDomainsEnabler';
import { LoadedSourcesRegistry } from '../cdtpDebuggee/registries/loadedSourcesRegistry';
import { ComponentCustomizationCallback } from './di';

export function bindAll(di: Container, callback: ComponentCustomizationCallback) {
    bind<IDOMInstrumentationBreakpoints>(di, TYPES.IDOMInstrumentationBreakpoints, CDTPDOMDebugger, callback);
    bind<IAsyncDebuggingConfigurer>(di, TYPES.IAsyncDebuggingConfiguration, CDTPAsyncDebuggingConfigurer, callback);
    bind<IScriptSourcesRetriever>(di, TYPES.IScriptSources, CDTPScriptSourcesRetriever, callback);
    bind<IStackTracePresentationLogicProvider>(di, TYPES.IStackTracePresentationLogicProvider, SmartStepLogic, callback);
    //  bind<IStackTracePresentationLogicProvider>(di, TYPES.IStackTracePresentationLogicProvider, SkipFilesLogic, callback);
    bind(di, TYPES.IEventsToClientReporter, EventSender, callback);
    bind(di, TYPES.ChromeDebugLogic, ChromeDebugLogic, callback);
    bind(di, TYPES.SourcesLogic, SourcesLogic, callback);
    bind(di, TYPES.CDTPScriptsRegistry, CDTPScriptsRegistry, callback);
    bind(di, TYPES.ClientToInternal, ClientToInternal, callback);
    bind(di, TYPES.InternalToClient, InternalToClient, callback);
    bind(di, TYPES.StackTracesLogic, StackTracesLogic, callback);
    bind(di, TYPES.BreakpointsLogic, BreakpointsLogic, callback);
    bind(di, TYPES.PauseOnExceptionOrRejection, PauseOnExceptionOrRejection, callback);
    bind(di, TYPES.Stepping, Stepping, callback);
    bind(di, TYPES.DotScriptCommand, DotScriptCommand, callback);
    bind(di, TYPES.BreakpointsRegistry, BreakpointsRegistry, callback);
    bind(di, TYPES.ReAddBPsWhenSourceIsLoaded, ReAddBPsWhenSourceIsLoaded, callback);
    bind(di, TYPES.PauseScriptLoadsToSetBPs, PauseScriptLoadsToSetBPs, callback);
    bind(di, TYPES.EventSender, EventSender, callback);
    bind(di, TYPES.DeleteMeScriptsRegistry, DeleteMeScriptsRegistry, callback);
    //  bind<BaseSourceMapTransformer>(di, TYPES.BaseSourceMapTransformer, BaseSourceMapTransformer, callback);
    //  bind<BasePathTransformer>(di, TYPES.BasePathTransformer, BasePathTransformer, callback);
    //  bind<IStackTracePresentationLogicProvider>(di, TYPES.IStackTracePresentationLogicProvider, SkipFilesLogic, callback);
    bind(di, TYPES.IDebugeeExecutionControl, CDTPDebugeeExecutionController, callback);
    bind(di, TYPES.IPauseOnExceptions, CDTPPauseOnExceptionsConfigurer, callback);
    bind(di, TYPES.IBreakpointFeaturesSupport, CDTPBreakpointFeaturesSupport, callback);
    bind(di, TYPES.IInspectDebugeeState, CDTPInspectDebugeeState, callback);
    bind(di, TYPES.IUpdateDebugeeState, CDTPUpdateDebugeeState, callback);
    bind(di, TYPES.BPRecipieInLoadedSourceLogic, BPRecipieAtLoadedSourceLogic, callback);
    bind(di, TYPES.SyncStepping, SyncStepping, callback);
    bind(di, TYPES.AsyncStepping, AsyncStepping, callback);
    // bind<cdtpBreakpointIdsRegistry>(di, cdtpBreakpointIdsRegistry, cdtpBreakpointIdsRegistry, callback);
    bind(di, TYPES.ExceptionThrownEventProvider, CDTPExceptionThrownEventsProvider, callback);
    bind(di, TYPES.ExecutionContextEventsProvider, CDTPExecutionContextEventsProvider, callback);
    bind(di, TYPES.LineColTransformer, LineColTransformer, callback);
    bind(di, TYPES.IBrowserNavigation, CDTPBrowserNavigator, callback);
    bind(di, TYPES.IScriptParsedProvider, CDTPOnScriptParsedEventProvider, callback);
    bind(di, TYPES.ICDTPDebuggerEventsProvider, CDTDebuggeeExecutionEventsProvider, callback);
    bind(di, TYPES.IDebugeeVersionProvider, CDTPDebugeeRuntimeVersionProvider, callback);
    bind(di, TYPES.ITargetBreakpoints, CDTPDebuggeeBreakpoints, callback);
    bind(di, TYPES.IConsoleEventsProvider, CDTPConsoleEventsProvider, callback);
    bind(di, TYPES.ILogEventsProvider, CDTPLogEventsProvider, callback);
    bind(di, TYPES.IDebugeeSteppingController, CDTPDebugeeSteppingController, callback);
    bind(di, TYPES.IBlackboxPatternsConfigurer, CDTPBlackboxPatternsConfigurer, callback);
    bind(di, TYPES.IDomainsEnabler, CDTPDomainsEnabler, callback);
    bind(di, LoadedSourcesRegistry, LoadedSourcesRegistry, callback);
}

function bind<T extends object>(container: Container, serviceIdentifier: interfaces.ServiceIdentifier<T>, newable: interfaces.Newable<T>, callback: ComponentCustomizationCallback): void {
    container.bind<T>(serviceIdentifier).to(newable).inSingletonScope().onActivation((_context, object) => {
        return callback(serviceIdentifier, object, _context.container.get);
        /// return new MethodsCalledLogger<T>(object, serviceIdentifier.toString()).wrapped();
    });
}
